# Generated by Django 5.0.14 on 2025-06-19 19:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('codigo_acesso', models.CharField(help_text='Código de acesso único para identificação do usuário na plataforma.', max_length=20, unique=True, verbose_name='Código de Acesso')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('comunidade', models.CharField(max_length=100, verbose_name='Comunidade')),
                ('perfil_pessoa', models.CharField(choices=[('PAROCO', 'Pároco'), ('CATEQUISTA', 'Catequista'), ('COORD_MINISTERIO', 'Coordenador de Ministério'), ('PASCOM', 'PASCOM'), ('FIEL', 'Fiel da Comunidade')], default='FIEL', max_length=20, verbose_name='Perfil do Usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Paroco',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
                ('identificador_paroco', models.CharField(max_length=100, unique=True, verbose_name='Identificador do Pároco')),
            ],
        ),
    ]
