# Generated by Django 5.0.14 on 2025-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo_acesso', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Código de Acesso')),
                ('comunidade', models.CharField(max_length=100, verbose_name='Comunidade')),
                ('perfil_usuario', models.CharField(choices=[('PAROCO', 'Pároco'), ('CATEQUISTA', 'Catequista'), ('COORD_MINISTERIO', 'Coordenador de Ministério'), ('PASCOM', 'PASCOM'), ('FIEL', 'Fiel da Comunidade')], default='FIEL', max_length=20, verbose_name='Perfil do Usuário')),
                ('identificador_paroco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificador do Pároco')),
            ],
        ),
    ]
