# Generated by Django 5.0.14 on 2025-06-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
