# Generated by Django 5.0.14 on 2025-06-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_pessoa_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
