# Generated by Django 5.0.14 on 2025-06-21 20:06

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pessoa_is_active_alter_pessoa_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
                ('objects', users.models.PessoaManager()),
            ],
        ),
    ]
