# Generated by Django 5.0.14 on 2025-06-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_pessoa_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='codigo_acesso',
            field=models.CharField(blank=True, editable=False, help_text='Código de acesso único para identificação do usuário na plataforma.', max_length=20, unique=True, verbose_name='Código de Acesso'),
        ),
    ]
