# Generated by Django 5.0.14 on 2025-06-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_pessoa_codigo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='null@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
