# Generated by Django 5.0.14 on 2025-06-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pessoa_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='perfil_pessoa',
            field=models.CharField(choices=[('PAROCO', 'Pároco'), ('CATEQUISTA', 'Catequista'), ('COORD_MINISTERIO', 'Coordenador de Ministério'), ('PASCOM', 'PASCOM'), ('FIEL', 'Fiel da Comunidade')], default=list, max_length=20, verbose_name='Perfil do Usuário'),
        ),
    ]
