# Generated by Django 5.0.14 on 2025-06-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_pessoa_perfil_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='perfis_adicionais',
            field=models.JSONField(blank=True, default=list, verbose_name='Perfis Adicionais'),
        ),
    ]
