# Generated by Django 5.0.14 on 2025-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pessoa_perfis_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='perfil_pessoa',
            field=models.CharField(choices=[('PAROCO', 'Pároco'), ('CATEQUISTA', 'Catequista'), ('COORD_MINISTERIO', 'Coordenador de Ministério'), ('PASCOM', 'PASCOM'), ('FIEL', 'Fiel da Comunidade')], default='FIEL', max_length=20, verbose_name='Perfil do Usuário'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='perfis_adicionais',
            field=models.CharField(blank=True, choices=[('PAROCO', 'Pároco'), ('CATEQUISTA', 'Catequista'), ('COORD_MINISTERIO', 'Coordenador de Ministério'), ('PASCOM', 'PASCOM'), ('FIEL', 'Fiel da Comunidade')], max_length=20, null=True, verbose_name='Perfis Adicionais'),
        ),
    ]
