# Generated by Django 5.0.14 on 2025-06-21 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0003_alter_pessoa_is_active_alter_pessoa_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssembleiaParoquial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_assembleia', models.CharField(max_length=100)),
                ('data_assembleia', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('paroco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembleias_paroquiais', to='users.paroco')),
                ('participantes', models.ManyToManyField(blank=True, help_text='Usuários convidados para a assembleia', related_name='assembleias_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='midias_galeria/', verbose_name='Arquivo da Mídia')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_coordenados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Formacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_formacao', models.CharField(max_length=100)),
                ('data_formacao', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('participantes', models.ManyToManyField(blank=True, help_text='Usuários convidados para a formação', related_name='formacoes_participadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_retiro', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('local', models.CharField(max_length=100)),
                ('numero_participantes', models.IntegerField(default=0)),
                ('limite_participantes', models.IntegerField(default=0)),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('logo', models.FileField(upload_to='midias_galeria/', verbose_name='Arquivo da Mídia')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros_coordenados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RetiroAcampamento',
        ),
    ]
