# Generated by Django 5.0.14 on 2025-06-21 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_assembleiaparoquial_eventos_formacoes_retiros_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retiros',
            new_name='RetiroAcampamento',
        ),
    ]
