# Generated by Django 5.0.14 on 2025-06-21 17:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_retiros_retiroacampamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='formacoes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='retiroacampamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retiroacampamento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CronogramaRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='events.retiroacampamento')),
            ],
        ),
        migrations.CreateModel(
            name='EquipeRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=100)),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='events.retiroacampamento')),
            ],
            options={
                'verbose_name': 'Equipe de Evento',
                'verbose_name_plural': 'Equipes de Eventos',
                'ordering': ['nome_equipe'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('X', 'Cancelada')], default='P', max_length=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='events.retiroacampamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_retiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento')),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=150, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_gateway', models.CharField(default='pendente', max_length=50)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('url_pagamento', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='events.inscricaoretiro')),
            ],
        ),
        migrations.CreateModel(
            name='ServoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='events.equiperetiro')),
                ('retiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to='events.retiroacampamento')),
                ('servo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servos_retiro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TentativaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('enviada', 'Enviada ao gateway'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('erro', 'Erro')], max_length=20)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('resposta_gateway', models.JSONField(blank=True, null=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='events.pagamentoretiro')),
            ],
        ),
    ]
