# Generated by Django 5.0.14 on 2025-06-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventos_created_at_eventos_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tentativapagamento',
            name='pagamento',
        ),
        migrations.DeleteModel(
            name='PagamentoRetiro',
        ),
        migrations.DeleteModel(
            name='TentativaPagamento',
        ),
    ]
