# Generated by Django 5.0.14 on 2025-06-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_tentativapagamento_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoretiro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inscricaoretiro',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inscricaoretiro',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
