# Generated by Django 5.0.14 on 2025-06-21 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_album', models.CharField(max_length=100, verbose_name='Nome do Álbum')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Álbum')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('id_pessoa_pascom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albuns_pascom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Álbum de Galeria',
                'verbose_name_plural': 'Álbuns de Galeria',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
