# Generated by Django 5.0.14 on 2025-06-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_midia', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio')], default='FOTO', max_length=10, verbose_name='Tipo de Mídia')),
                ('arquivo', models.FileField(upload_to='midias_galeria/', verbose_name='Arquivo da Mídia')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='pascom.albumgaleria')),
                ('id_pessoa_pascom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_pascom', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mídia de Galeria',
                'verbose_name_plural': 'Mídias de Galeria',
                'ordering': ['-data_upload'],
            },
        ),
    ]
