# Generated by Django 5.0.14 on 2025-06-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascom', '0002_midiagaleria'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiagaleria',
            name='nome_arquivo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo'),
        ),
    ]
