# Generated by Django 5.0.14 on 2025-06-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_remove_tentativapagamento_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comprovante_pagamento', models.FileField(blank=True, null=True, upload_to='comprovantes_pagamento/', verbose_name='Comprovante de Pagamento')),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=150, null=True)),
                ('gateway_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_gateway', models.CharField(default='pendente', max_length=50)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('url_pagamento', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('estornado', 'Estornado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='events.inscricaoretiro')),
            ],
        ),
        migrations.CreateModel(
            name='TentativaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('criada', 'Criada'), ('enviada', 'Enviada ao gateway'), ('sucesso', 'Sucesso'), ('falha', 'Falha'), ('erro', 'Erro')], max_length=20)),
                ('data_tentativa', models.DateTimeField(auto_now_add=True)),
                ('resposta_gateway', models.JSONField(blank=True, null=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='finances.pagamentoretiro')),
            ],
        ),
    ]
