# Generated by Django 5.0.14 on 2025-06-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SacramentoParoquial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sacramento', models.CharField(choices=[('BATISMO', 'Batismo'), ('CRISM', 'Crisma'), ('ADORACAO_EUCARISTICA', 'Adoração Eucarística'), ('MATRIMONIO', 'Matrimônio'), ('ORDENACAO', 'Ordenação'), ('UNCAO_DOS_ENFERMOS', 'Unção dos Enfermos'), ('RECONCILIACAO', 'Reconciliação')], default='BATISMO', max_length=20, verbose_name='Nome do Sacramento')),
                ('data_agendamento', models.DateField(auto_now_add=True, verbose_name='Data do Sacramento')),
                ('data_sacramento', models.DateTimeField(verbose_name='Data do Sacramento')),
                ('envolvidos', models.CharField(help_text='Lista de pessoas ou grupos envolvidos no sacramento, separados por vírgula.', max_length=255, null=True, verbose_name='Envolvidos')),
                ('aprovado', models.BooleanField(default=True, help_text='Indica se o sacramento foi aprovado pelo pároco responsável.', verbose_name='Aprovado')),
            ],
        ),
    ]
