# Generated by Django 5.0.14 on 2025-06-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sacraments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacramentoparoquial',
            name='paroco_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.paroco', verbose_name='Pároco Responsável'),
        ),
    ]
