# Generated by Django 5.0.14 on 2025-06-19 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacraments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacramentoparoquial',
            name='aprovado',
        ),
        migrations.CreateModel(
            name='AgendamentoSacramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Agendamento')),
                ('data_solicitada', models.DateTimeField(help_text='Data em que o sacramento foi solicitado.', verbose_name='Data Solicitada')),
                ('aprovado', models.BooleanField(default=False, help_text='Indica se o sacramento foi aprovado pelo pároco responsável.', verbose_name='Aprovado')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_sacramento', to=settings.AUTH_USER_MODEL, verbose_name='Pessoa')),
                ('sacramento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='sacraments.sacramentoparoquial', verbose_name='Sacramento')),
            ],
            options={
                'verbose_name': 'Agendamento de Sacramento',
                'verbose_name_plural': 'Agendamentos de Sacramentos',
            },
        ),
    ]
