# Generated by Django 5.0.14 on 2025-06-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacraments', '0003_remove_sacramentoparoquial_aprovado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sacramentoparoquial',
            name='data_agendamento',
        ),
        migrations.RemoveField(
            model_name='sacramentoparoquial',
            name='data_sacramento',
        ),
        migrations.RemoveField(
            model_name='sacramentoparoquial',
            name='envolvidos',
        ),
        migrations.AddField(
            model_name='agendamentosacramento',
            name='envolvidos',
            field=models.CharField(help_text='Lista de pessoas ou grupos envolvidos no sacramento, separados por vírgula.', max_length=255, null=True, verbose_name='Envolvidos'),
        ),
        migrations.AlterField(
            model_name='sacramentoparoquial',
            name='nome_sacramento',
            field=models.CharField(choices=[('BATISMO', 'Batismo'), ('CONFISSAO', 'Confissão'), ('CRISMA', 'Crisma'), ('ADORACAO_EUCARISTICA', 'Adoração Eucarística'), ('MATRIMONIO', 'Matrimônio'), ('ORDENACAO', 'Ordenação'), ('UNCAO_DOS_ENFERMOS', 'Unção dos Enfermos'), ('RECONCILIACAO', 'Reconciliação')], default='BATISMO', max_length=20, verbose_name='Nome do Sacramento'),
        ),
    ]
