# Generated by Django 5.0.14 on 2025-06-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacraments', '0004_remove_sacramentoparoquial_data_agendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentosacramento',
            name='envolvidos',
        ),
    ]
